POSSIBLE_CUSTOM_PROMPTS = [
    "Include a question that could come up in a conversation between two classmates preparing for university.",
    "Create a question inspired by a real-life decision a teenager might have to make.",
    "Include a dialogue that takes place at a career counseling session.",
    "Add a sentence where students must pick the most appropriate word to show contrast.",
    "Include a school setting where a teacher gives feedback to a student.",
    "Make one question sound like a university entrance interview.",
    "Use a situation where someone is giving advice about studying abroad.",
    "Include a scenario at a graduation party.",
    "Create a gap-fill that could reflect a social media post by a teenager.",
    "Use a conversation between friends about choosing a major.",
    "Include a context where a student expresses personal opinions in a polite way.",
    "Write a question based on planning a class farewell trip.",
    "Incorporate a sentence that might appear in a formal letter to a school principal.",
    "Include a peer-to-peer conversation on dealing with exam stress.",
    "Make one sentence sound like something from a school debate.",
    "Include a student asking a teacher for a recommendation letter.",
    "Add a sentence where someone is giving instructions for an important event.",
    "Use an example where a student reflects on their high school years.",
    "Include a question that sounds like it's from a career expo booth.",
    "Use a dialogue where someone gives or receives constructive criticism.",
    "Include a scenario in a mock job interview for students.",
    "Create a situation where students talk about their future goals.",
    "Use a casual conversation between siblings discussing post-graduation plans.",
    "Incorporate a question involving expressions of encouragement or motivation.",
    "Add a phrase that could appear in a school magazine article.",
    "Include a friendly chat about volunteer work opportunities.",
    "Use a situation where someone apologizes for missing an important school event.",
    "Add a question based on a teacher's announcement.",
    "Use a short monologue from a farewell speech.",
    "Include a situation where students plan a community service project.",
    "Use a realistic high school setting where someone is late to class.",
    "Include an announcement that could be heard during a school assembly.",
    "Create a casual text message between classmates working on a group project.",
    "Use a sentence from a thank-you note to a mentor.",
    "Include a classroom interaction about exam preparation tips.",
    "Use a sentence that might come from a college application essay.",
    "Include a public notice about changes to exam schedules.",
    "Create a scenario where a friend is asking for emotional support.",
    "Add a question that could reflect a school orientation session.",
    "Use a setting where someone explains how to prepare a CV.",
    "Include a problem-solving conversation between two classmates.",
    "Write a sentence a student might use when giving a presentation.",
    "Use a situation in a mock IELTS speaking practice.",
    "Include a question based on feedback from a mock test result.",
    "Create a sentence where someone discusses the benefits of learning English.",
    "Include an interaction where someone is asking for help with homework.",
    "Add a situation where students talk about balancing study and hobbies.",
    "Use a context where someone expresses disagreement politely.",
    "Include a discussion about environmental topics from a school project.",
    "Use a quote that could be printed in a school yearbook.",
    "Include a dialogue that might take place during a cultural exchange.",
    "Use a setting at an English club meeting.",
    "Include a humorous exchange between friends in the school canteen.",
    "Create a scenario that shows teamwork among classmates.",
    "Use a context where someone shares their biggest challenge in high school.",
    "Include a sentence describing a memory from the first day of school.",
    "Add a short conversation during a school talent show.",
    "Include a dialogue from a discussion about internet safety.",
    "Use a realistic chat where students discuss study methods.",
    "Include a question related to expressing hope for the future.",
    "Use a setting where students prepare for a scholarship interview.",
    "Include a moment of reflection before taking the national exam.",
    "Create a sentence from a student council meeting.",
    "Use a context involving helping a friend solve a personal problem.",
    "Include a sentence where someone talks about a recent book they read.",
    "Use a setting where someone describes their dream job.",
    "Include a conversation between students about their internship experiences.",
    "Use a polite request during a formal school event.",
    "Create a realistic error students often make in casual speech.",
    "Use a context from a school campaign about recycling.",
    "Include a chat about preparing for an English competition.",
    "Create a scenario that teaches how to give a compliment naturally.",
    "Use a short speech opening introducing a class project.",
    "Include a humorous miscommunication that still makes sense grammatically.",
    "Add a phrase that might come from a motivational video for students.",
    "Include an interaction where someone gives directions at school.",
    "Use a setting involving organizing a school event.",
    "Include a short student blog post excerpt.",
    "Create a comment that sounds like part of a YouTube video on study tips.",
    "Include a question from a mock public speaking contest.",
    "Use a casual compliment in the middle of a conversation.",
    "Include a classroom instruction that's slightly ambiguous.",
    "Add a sentence from a peer evaluation form.",
    "Include a joke or pun with a missing word that fits grammatically.",
    "Create a motivational statement with one key word missing.",
    "Include a thank-you message from a student to a favorite teacher.",
    "Use a diary entry from a student's point of view.",
    "Add a sentence from a campaign to encourage reading.",
    "Include an informal conversation about personal growth.",
    "Use a context where students compare different career paths.",
    "Include a line from a farewell speech to classmates.",
    "Use a realistic online chat between students studying together.",
    "Include a question inspired by a school poster.",
    "Use a short teacher-student exchange from a speaking class.",
    "Include a correction of a common misuse of informal phrases.",
    "Add a prompt for choosing the best summary of a given idea.",
    "Use a context from a scholarship motivation letter.",
    "Include a brief reflection on what it means to be successful.",
    "Create a natural sentence that uses everyday expressions of agreement.",
    "Include a phrase where someone describes a personal achievement.",
    "Use a conversation about time management tips.",
    "Include an excerpt that might come from a school newsletter article.",
    "Add a statement about setting goals and staying motivated.",
    "Include a question showing the importance of empathy in communication.",
]


DOK_DESCRIPTIONS = {
  1: """- **DOK Level 1 (Recall):** Focus on recognizing or recalling basic English facts, such as word meaning, grammar forms, or sound patterns.""",
  2: """- **DOK Level 2 (Skill/Concept):** Questions require applying learned rules or concepts to new examples.""",
  3: """- **DOK Level 3 (Strategic Thinking):** Include deeper reasoning, contextual inference, or decision making.""",
}