version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - backend-media:/app/backend/media
    ports:
      - "8000:8000"
    env_file:
    - backend/.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 5s
      timeout: 2s
      retries: 120
    restart: on-failure
  
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
    - frontend/.env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      - BACKEND_URL=http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure

volumes:
  backend-media:
  postgres-data:

networks:
  app-network:
    driver: bridge