services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"  # Prometheus dashboard
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "9091:3000"  # Grafana dashboard
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
